// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BigTed.OnTheTelly {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("DownloaderViewController")]
	public partial class DownloaderViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_CloseButton;
		
		private MonoTouch.UIKit.UIImageView __mt_ImageView;
		
		private MonoTouch.UIKit.UIProgressView __mt_ProgressBar;
		
		private MonoTouch.UIKit.UILabel __mt_SubLabel;
		
		private MonoTouch.UIKit.UILabel __mt_TitleLabel;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("CloseButton")]
		private MonoTouch.UIKit.UIButton CloseButton {
			get {
				this.__mt_CloseButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("CloseButton")));
				return this.__mt_CloseButton;
			}
			set {
				this.__mt_CloseButton = value;
				this.SetNativeField("CloseButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("ImageView")]
		private MonoTouch.UIKit.UIImageView ImageView {
			get {
				this.__mt_ImageView = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("ImageView")));
				return this.__mt_ImageView;
			}
			set {
				this.__mt_ImageView = value;
				this.SetNativeField("ImageView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("ProgressBar")]
		private MonoTouch.UIKit.UIProgressView ProgressBar {
			get {
				this.__mt_ProgressBar = ((MonoTouch.UIKit.UIProgressView)(this.GetNativeField("ProgressBar")));
				return this.__mt_ProgressBar;
			}
			set {
				this.__mt_ProgressBar = value;
				this.SetNativeField("ProgressBar", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("SubLabel")]
		private MonoTouch.UIKit.UILabel SubLabel {
			get {
				this.__mt_SubLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("SubLabel")));
				return this.__mt_SubLabel;
			}
			set {
				this.__mt_SubLabel = value;
				this.SetNativeField("SubLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("TitleLabel")]
		private MonoTouch.UIKit.UILabel TitleLabel {
			get {
				this.__mt_TitleLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("TitleLabel")));
				return this.__mt_TitleLabel;
			}
			set {
				this.__mt_TitleLabel = value;
				this.SetNativeField("TitleLabel", value);
			}
		}
	}
}
