// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BigTed.OnTheTelly {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegate")]
	public partial class AppDelegate {
		
		private MonoTouch.UIKit.UIWindow __mt_window;
		
		private MonoTouch.UIKit.UITabBarController __mt_tabbarController;
		
		private MonoTouch.UIKit.UINavigationController __mt_downloadNavigationController;
		
		private MonoTouch.UIKit.UINavigationController __mt_queueNavigationController;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				this.__mt_window = ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
				return this.__mt_window;
			}
			set {
				this.__mt_window = value;
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("tabbarController")]
		private MonoTouch.UIKit.UITabBarController tabbarController {
			get {
				this.__mt_tabbarController = ((MonoTouch.UIKit.UITabBarController)(this.GetNativeField("tabbarController")));
				return this.__mt_tabbarController;
			}
			set {
				this.__mt_tabbarController = value;
				this.SetNativeField("tabbarController", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("downloadNavigationController")]
		private MonoTouch.UIKit.UINavigationController downloadNavigationController {
			get {
				this.__mt_downloadNavigationController = ((MonoTouch.UIKit.UINavigationController)(this.GetNativeField("downloadNavigationController")));
				return this.__mt_downloadNavigationController;
			}
			set {
				this.__mt_downloadNavigationController = value;
				this.SetNativeField("downloadNavigationController", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("queueNavigationController")]
		private MonoTouch.UIKit.UINavigationController queueNavigationController {
			get {
				this.__mt_queueNavigationController = ((MonoTouch.UIKit.UINavigationController)(this.GetNativeField("queueNavigationController")));
				return this.__mt_queueNavigationController;
			}
			set {
				this.__mt_queueNavigationController = value;
				this.SetNativeField("queueNavigationController", value);
			}
		}
	}
}
