// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BigTed.OnTheTelly {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("ProgramDetailViewController")]
	public partial class ProgramDetailViewController {
		
		private MonoTouch.UIKit.UIView __mt_view;
		
		private MonoTouch.UIKit.UIButton __mt_DownloadButton;
		
		private MonoTouch.UIKit.UIImageView __mt_ImageView;
		
		private MonoTouch.UIKit.UIButton __mt_WatchButton;
		
		private MonoTouch.UIKit.UILabel __mt_TitleLabel;
		
		private MonoTouch.UIKit.UITextView __mt_SubtitleLabel;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("view")]
		private MonoTouch.UIKit.UIView view {
			get {
				this.__mt_view = ((MonoTouch.UIKit.UIView)(this.GetNativeField("view")));
				return this.__mt_view;
			}
			set {
				this.__mt_view = value;
				this.SetNativeField("view", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("DownloadButton")]
		private MonoTouch.UIKit.UIButton DownloadButton {
			get {
				this.__mt_DownloadButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("DownloadButton")));
				return this.__mt_DownloadButton;
			}
			set {
				this.__mt_DownloadButton = value;
				this.SetNativeField("DownloadButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("ImageView")]
		private MonoTouch.UIKit.UIImageView ImageView {
			get {
				this.__mt_ImageView = ((MonoTouch.UIKit.UIImageView)(this.GetNativeField("ImageView")));
				return this.__mt_ImageView;
			}
			set {
				this.__mt_ImageView = value;
				this.SetNativeField("ImageView", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("WatchButton")]
		private MonoTouch.UIKit.UIButton WatchButton {
			get {
				this.__mt_WatchButton = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("WatchButton")));
				return this.__mt_WatchButton;
			}
			set {
				this.__mt_WatchButton = value;
				this.SetNativeField("WatchButton", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("TitleLabel")]
		private MonoTouch.UIKit.UILabel TitleLabel {
			get {
				this.__mt_TitleLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("TitleLabel")));
				return this.__mt_TitleLabel;
			}
			set {
				this.__mt_TitleLabel = value;
				this.SetNativeField("TitleLabel", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("SubtitleLabel")]
		private MonoTouch.UIKit.UITextView SubtitleLabel {
			get {
				this.__mt_SubtitleLabel = ((MonoTouch.UIKit.UITextView)(this.GetNativeField("SubtitleLabel")));
				return this.__mt_SubtitleLabel;
			}
			set {
				this.__mt_SubtitleLabel = value;
				this.SetNativeField("SubtitleLabel", value);
			}
		}
	}
}
